version: "3.7"
services:
  nbk:
    build:
      context: ./
      dockerfile: Dockerfile
      # args:
        # - PIP_EXTRA_INDEX_URL=${BUILD_ARG_PIP_EXTRA_INDEX_URL}
    volumes:
      - ./:/app
    ports:
      - "0.0.0.0:8899:8899"
    entrypoint: [jupyter-lab, --ip=0.0.0.0, --port=8899, --no-browser, --allow-root]
